const fs = require("node:fs/promises");
const path = require("node:path");
const { withDangerousMod, withXcodeProject } = require("@expo/config-plugins");

const BUNDLE_PHASE_NAME = "Bundle React Native code and images";

const xcodeEnv = `# Generated by plugins/withNixXcodeEnvironment.js. Do not edit.

if [ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
  . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
elif [ -f "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
  . "$HOME/.nix-profile/etc/profile.d/nix.sh"
fi

if ! command -v nix >/dev/null 2>&1; then
  echo "Nix is required to build the iOS app." >&2
  exit 1
fi

_lt_nix_env="$(nix print-dev-env --extra-experimental-features 'nix-command flakes' "$PROJECT_DIR/..#ios")" || {
  echo "Could not load the iOS Nix development environment." >&2
  exit 1
}
eval "$_lt_nix_env" || exit 1
unset _lt_nix_env

NODE_BINARY="$(command -v node)" || {
  echo "Node is missing from the iOS Nix development environment." >&2
  exit 1
}
export NODE_BINARY
`;

function useBashForBundlePhase(project) {
  const target = project.getFirstTarget().uuid;
  const phases = project.pbxNativeTargetSection()[target].buildPhases;
  const bundlePhase = phases.find((phase) => phase.comment === BUNDLE_PHASE_NAME);
  const buildPhase = bundlePhase &&
    project.hash.project.objects.PBXShellScriptBuildPhase?.[bundlePhase.value];
  if (!buildPhase) throw new Error(`Could not find ${BUNDLE_PHASE_NAME} build phase`);
  buildPhase.shellPath = "/bin/bash";
  return project;
}

module.exports = function withNixXcodeEnvironment(config) {
  config = withDangerousMod(config, ["ios", async (config) => {
    await fs.writeFile(
      path.join(config.modRequest.platformProjectRoot, ".xcode.env"),
      xcodeEnv
    );
    return config;
  }]);

  return withXcodeProject(config, (config) => {
    config.modResults = useBashForBundlePhase(config.modResults);
    return config;
  });
};

module.exports.xcodeEnv = xcodeEnv;
module.exports.useBashForBundlePhase = useBashForBundlePhase;
