const fs = require("node:fs/promises");
const path = require("node:path");
const { withDangerousMod, withXcodeProject } = require("@expo/config-plugins");

const BUNDLE_PHASE_NAME = "Bundle React Native code and images";
const BUNDLE_WRAPPER_MARKER = "# Run the Expo bundle phase in the iOS Nix shell.";
const BUNDLE_SCRIPT_DELIMITER = "LT_NIX_XCODE_BUNDLE_SCRIPT";

const xcodeEnv = `# Generated by plugins/withNixXcodeEnvironment.js. Do not edit.

if [ -z "\${IN_NIX_SHELL:-}" ]; then
  if [ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  elif [ -f "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
    . "$HOME/.nix-profile/etc/profile.d/nix.sh"
  fi
fi

if ! command -v nix >/dev/null 2>&1; then
  echo "Nix is required to build the iOS app." >&2
  exit 1
fi

lt_run_in_nix() {
  local _lt_project_root
  _lt_project_root="$(cd "$PROJECT_DIR/.." && pwd -P)" || return 1
  nix develop --extra-experimental-features 'nix-command flakes' "$_lt_project_root#ios" --command "$@"
}

# React Native's bundle phase sources this file again inside the Nix shell.
NODE_BINARY="$(command -v node || true)"
export NODE_BINARY
`;

function wrapBundlePhaseInNix(project) {
  const target = project.getFirstTarget().uuid;
  const phases = project.pbxNativeTargetSection()[target].buildPhases;
  const bundlePhase = phases.find((phase) => phase.comment === BUNDLE_PHASE_NAME);
  const buildPhase = bundlePhase &&
    project.hash.project.objects.PBXShellScriptBuildPhase?.[bundlePhase.value];
  if (!buildPhase) throw new Error(`Could not find ${BUNDLE_PHASE_NAME} build phase`);
  if (!buildPhase.shellScript.includes(BUNDLE_WRAPPER_MARKER)) {
    const originalScript = JSON.parse(buildPhase.shellScript);
    if (originalScript.includes(BUNDLE_SCRIPT_DELIMITER)) {
      throw new Error(`Unexpected ${BUNDLE_SCRIPT_DELIMITER} in ${BUNDLE_PHASE_NAME}`);
    }
    const wrappedScript = [
      "set -e",
      BUNDLE_WRAPPER_MARKER,
      'source "$PODS_ROOT/../.xcode.env"',
      `lt_run_in_nix bash -c "$(cat <<'${BUNDLE_SCRIPT_DELIMITER}'`,
      originalScript.trimEnd(),
      BUNDLE_SCRIPT_DELIMITER,
      ')"',
    ].join("\n");
    buildPhase.shellScript = JSON.stringify(wrappedScript);
  }
  buildPhase.shellPath = "/bin/bash";
  return project;
}

module.exports = function withNixXcodeEnvironment(config) {
  config = withDangerousMod(config, ["ios", async (config) => {
    await fs.writeFile(
      path.join(config.modRequest.platformProjectRoot, ".xcode.env"),
      xcodeEnv
    );
    return config;
  }]);

  return withXcodeProject(config, (config) => {
    config.modResults = wrapBundlePhaseInNix(config.modResults);
    return config;
  });
};

module.exports.xcodeEnv = xcodeEnv;
module.exports.wrapBundlePhaseInNix = wrapBundlePhaseInNix;
